### ISSUE TITLE
Two questions

### ISSUE THREAD

**Issue by kljzndx** [liesauer/Free-SS-SSR#1]
闲的没事过来看看，碰巧看到俩bug。。。   
     
1. 为啥不能自动删除掉那些ping为0的梯子呢
2. 为啥现在很多梯子的区域都是 "UN"

**Comment by kljzndx** [comment]
补充一句，如不解决我就Unstar🌹🐓

**Comment by liesauer** [comment]
目前的ping检测的话是从我服务器直连socket检测的，0的话代表检测超时，但我不确定在用户手里能不能连，所以现阶段是没做过滤的，目前项目重构中，且后续会多加几个爬虫，会加入ping延迟过滤以及ip ban检测
关于区域为UN，现在的字段都是直接爬来用的，没做数据处理，所以这是源站没有检测出来，重构后的版本加入ip2region库进行检测问题也不大，望继续支持，谢谢！
